server.port=8084

spring.web.resources.add-mappings=false



spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

spring.jpa.defer-datasource-initialization=true
spring.sql.init.data-locations=classpath:/sql/sql.sql

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000

